#define CHAR_ERR_SUCCESS		0
#define CHAR_ERR_OUT_OF_MEMORY		2
#define CHAR_ERR_SETUP_FAILED		3
#define CHAR_ERR_READ_ERROR		4
#define CHAR_ERR_REQUEST		5

#define CHAR_ERR_FS_ALREADY_REGISTERED	100
#define CHAR_ERR_FS_NOT_SUPPORTED	101
#define CHAR_ERR_UNSUPPORTED_FS		102

#define CHAR_ERR_INVALID_PARTITION	120
#define CHAR_ERR_INVALID_HDD		121
#define CHAR_ERR_MOUNTING		122
#define CHAR_ERR_DRIVER_UNEXPECTED_END	123
#define CHAR_ERR_NO_DRIVES_FOUND	124
