#define FS_EXPORT_MOUNT_FS	0
#define FS_EXPORT_UNMOUNT_FS	1
#define FS_EXPORT_ACCESSFILE	2
#define FS_EXPORT_READFILEAT	3
#define FS_EXPORT_READFILECHUNK	4
#define FS_EXPORT_WRITEFILEAT	5
#define FS_EXPORT_FINDNEXTFILE	6
#define FS_EXPORT_FILEINFO	7
