#define FS_ERR_SUCCESS		0
#define FS_ERR_READ		201
#define FS_ERR_COMMUNICATION	202
#define FS_ERR_READING_SECTOR	203
#define FS_ERR_INVALID_ARGUMENT	204
#define FS_ERR_CORRUPT		205

#define FS_ERR_OUT_OF_MEMORY	300
